language: java
jdk:
  - oraclejdk8
  - oraclejdk7

# Encrypted global secret variables (passwords and keys)
env:
  global:
    - secure: dH6yhuE+U8wKJbfRk51CJ6tG+j5PVllx6OHD4rXPb9jKVw/H3AiDsUnWnnBJCkL2mgSMeSDmOlS298kqKXPl7QHRWbx50dZebcEm8k5KLvkB4eW/wozZ9VaZG4ZUpAvV1v7dYpcQi2kPxIkxpZMpA1kPT12ukrLKIFbVD3W+1FvVEWCcbXRduhBF4dklwL5G70XkwM8DNIkAhsynAgellbedlcf9ScBNWpnBBKHLXJaHNxfrPyB4GQEvplhrr03L0zqDIFih56YJJjUuJ6N+V3i0gTIexmKdrBp4VTJzYNZE8GJad9zbSTdoYqF8r9mqWhWs5tmz17juWLyb3Ludl1Syb1UKOwDM0LmmLSeK1MaDlnv8eoKODGiZD8Of1k77rvEL7066PdMsPbxCF1xWm25hdrNERhB1WYxprbZtS5uqc6yRedGPUDxRW2WfOv1ns3FvaP+GBRmG9Qq2hUldVlbJXSSprC8wX/FUokeEO4Mg76JNnOv9F/HMWy7rT9dOPZBWyvpdF1pP2d1nrrmOCj9aYf27MldoqecRBShjQmn6nldJx7DsCvg69rt23pU1uPXIoGK18fEZwBUOn8PFhu2aCA/K4YlH3G6oD0cj7WYGPl1oFoTMZBoPgxC7+kVV2ehN4ZS7To6vRZsh6WJ49eTW/BmFKuyBc+dUBr2N5m8=
    - secure: lByGSM4Jgi24/r0GaWmI5H38R417JF3HRZB/ThJeLC9SVLmzn894AKcZGBcb6Z5UDA0Eo3GohuSnmGHX0zGk78M5+9U2Mh3mO9gOb3288pYa2nsDKpSDNNdJIjDVR1YZAbuJjW7JzT77HNCN4mEfruZTwQdG8eUgDzA29+21L2GevzaaYdrbqWliveAYeALOGapQ9Tuu2cXsWmvWs++RUrJD+vzgVuY7ncH6IFCHo01J4TzUdikHDpqJXkCC/PJNb7WicNv2JU88AZnupeqVQt811W0b8IZ9oJ5kPnfvLDzf1pNJNW8vc2YzGsZPhtkwwXz0mJ25zW+UZ5xIVcAeOCJii9yPHpuj5ikWxl7Rh+/XpPuJMiOSzhPJxBwpebgwxnsj5MjxtMYEy1OqsqKskJ7lgiqrT1MMey7WNeIKvGep/FfIvNc0IQD5uIo6Jq1DKRmcD/NwRjCtvu56SmyIdB+qfiFCOue0YwkvCxtL3g4iJbGN1pxkBubs76cbJ3Y/fJJ4OC3beBFu/LZB5nk59oLROnJ9z6fcJAufhsmwREV+OHPgRk0VjjY6OcDLT7wanPmi73TcjntC489GOzMscFYmTAYrck6s2IfSZk9iZHLk29KA/f6NQdzflRq94Z/bZMf3fMK/PAWfx2vSPPHO/tHuu6Gd7YOBz+wRgqcKCOc=
    - secure: q7GMVOkMsmuCXEBKAaxwwn6flqGNZBeLcM2IpGzfqdU+k/sOcgjxKDzKtsmMBEdCew3QdbfRLWaKelZ9/8PhcLGLlQYwoQ550rifevBK3LABFNOiZ5CrWGiJ0G+RyK65T9kkIN6zsu73gGif+o3da+q2iOIsdcyaMhN/2Bx59NgB7VDiYGyB/MPQdg+yVoBFe/S8jpKsomBezH7Co3T6UlwtTpXkO/Ekj8TgWa8AcSbzZZ4pilXqB4j8wCjtXKswO0/w1b1oRw4hiooL2JymnhLPSzX+OI1kOoVvvvAO3ughZzD6kk/b+w9RH+KgZnflZ8EoY3OjWR+6/Dbo40/j0wK23JafLKE4s6N8ma/HMZEA147NZTzGr/mGF7wy2Y1vw1OOoWq8bzCwD5BJ4taVlHzTfcXcd51ih2qxeh0/HCRWrhtyuk/gKbAKGr0nXUI/xRHKCmqMk/jQjLnTBY+JoIm/FRYusK0D2VPQUES9TYgFN1xkm+xAGkmSzU9UcFsFnK1BeyoKjtX6/3ELabIus2zu1p3KLi69pwVfeFdIjE3kKkZ/O5IYNp8BwjSXs6FeJtSvfL9I3Jq3LMxTND1z/dPsjwOOAo4kIKVethdEhwthWQpXYe5/MBpsGOCqPPKLFY5dGHXgw7KZ2i5aooPVj87Ig6e4ZFLVeISKHkMJKd0=
  
# Build settings
sudo: false
notifications:
  email: false

# Skip default travis installation task
install:
  - echo "skip default gradlew assemble"

# Execute custom script instead of default travis execution
script:
  - ./gradlew check jacocoTestReport coveralls
branches:
  only:
  - develop
  - master
  
# Output all test results in case of the build failure
after_failure:
  - cat build/test-results/test/*.xml

# Deploy snapshot version or release version, depending on the branch (that is decided in gradle, see deployment.gradle)
deploy:
  provider: script
  script: ./gradlew travisDeploy
  skip_cleanup: true
  on:
    all_branches: true
    jdk: oraclejdk8

# Used to avoid uploading the cache after every build, see https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/repositories/